hyperparameter_space:
    num_h_layers:
        value: 10  # A constant
    h_size:
        value: 1024 
        
    num_epochs:
        value: 10
    b_size:
        value: 1024
    lr:
        loguniform: [1e-5, 1e-2]  # log-uniform random sample (for exponential ranges)
    eval_interval:
        value: 1e5
        
    T:
        value: 1000  
    diffusion_schedule:
        value: 'cosine'  #'linear'

model_constants:
    model_name: 'ffn'
    dataset_name: 'mnist'
    num_classes: 10
    resume_from_checkpoint:  # Leave empty for None
    save_dir: 'saved_models/test'
    do_test: 0

